[package]
name = "isbn2"
version = "0.3.1"
authors = ["Jihyeok Seo <limeburst@ridi.com>", "Philippe Solodov <solop1906@gmail.com>"]
description = "A library for handling ISBNs."
license = "MIT"
repository = "https://github.com/philippeitis/isbn-rs"
edition = "2018"

[build-dependencies]
codegen = "0.1"
roxmltree = "0.13.0"

[dependencies]
arrayvec = { version = "0.5.2", default-features = false }
